/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../src/views/AboutView.vue')['default']
    BlackLayout: typeof import('./../src/views/layout/BlackLayout.vue')['default']
    ComplexTable: typeof import('./../src/views/ComplexTable.vue')['default']
    DicStore: typeof import('./../src/views/dicStore.vue')['default']
    DownLoad: typeof import('./../src/views/downLoad.vue')['default']
    Echart: typeof import('./../src/views/Echart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    Form: typeof import('./../src/views/Form.vue')['default']
    HomeView: typeof import('./../src/views/HomeView.vue')['default']
    IndexBar: typeof import('./../src/views/IndexBar.vue')['default']
    NavLayout: typeof import('./../src/views/layout/NavLayout.vue')['default']
    NotFoundView: typeof import('./../src/views/NotFoundView.vue')['default']
    RefreshList: typeof import('./../src/views/RefreshList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SBack: typeof import('./../src/components/SBack.vue')['default']
    SComplexTable: typeof import('./../src/components/SComplexTable.vue')['default']
    SEchart: typeof import('./../src/components/SEchart.vue')['default']
    SForm: typeof import('./../src/components/SForm.vue')['default']
    SIndexBar: typeof import('./../src/components/SIndexBar.vue')['default']
    STable: typeof import('./../src/components/STable.vue')['default']
    SUpload: typeof import('./../src/components/SUpload.vue')['default']
    SwipeTag: typeof import('./../src/components/SwipeTag.vue')['default']
    Table: typeof import('./../src/views/Table.vue')['default']
    TableSpan: typeof import('./../src/views/TableSpan.vue')['default']
    Upload: typeof import('./../src/views/Upload.vue')['default']
    Websocket: typeof import('./../src/views/Websocket.vue')['default']
  }
}
