/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../src/views/AboutView.vue')['default']
    BlackLayout: typeof import('./../src/views/layout/BlackLayout.vue')['default']
    Echart: typeof import('./../src/views/Echart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HomeView: typeof import('./../src/views/HomeView.vue')['default']
    NotFoundView: typeof import('./../src/views/NotFoundView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    STable: typeof import('./../src/components/STable.vue')['default']
    Table: typeof import('./../src/views/Table.vue')['default']
  }
}
