export const findListData = {
  datas: [
    {
      werksCode: null,
      totalNum: 0.0,
      prodNum: 0.0,
      prodNumTotal: 223.0,
      prodRate: 0.0,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 0.0,
      partsNumTotal: 1911.0,
      partsRate: 0.0,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '08',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 372.0,
      prodNum: 0.0,
      prodNumTotal: 223.0,
      prodRate: 0.0,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 372.0,
      partsNumTotal: 1911.0,
      partsRate: 19.47,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '09',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 240.0,
      prodNum: 87.0,
      prodNumTotal: 223.0,
      prodRate: 39.01,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 153.0,
      partsNumTotal: 1911.0,
      partsRate: 8.01,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '10',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 433.0,
      prodNum: 115.0,
      prodNumTotal: 223.0,
      prodRate: 51.57,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 318.0,
      partsNumTotal: 1911.0,
      partsRate: 16.64,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '11',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 71.0,
      prodNum: 3.0,
      prodNumTotal: 223.0,
      prodRate: 1.35,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 68.0,
      partsNumTotal: 1911.0,
      partsRate: 3.56,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '12',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 66.0,
      prodNum: 0.0,
      prodNumTotal: 223.0,
      prodRate: 0.0,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 66.0,
      partsNumTotal: 1911.0,
      partsRate: 3.45,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '13',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 416.0,
      prodNum: 0.0,
      prodNumTotal: 223.0,
      prodRate: 0.0,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 416.0,
      partsNumTotal: 1911.0,
      partsRate: 21.77,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '14',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 172.0,
      prodNum: 0.0,
      prodNumTotal: 223.0,
      prodRate: 0.0,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 172.0,
      partsNumTotal: 1911.0,
      partsRate: 9.0,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '15',
      mhourArea: null,
      enum: 0.0
    },
    {
      werksCode: null,
      totalNum: 364.0,
      prodNum: 18.0,
      prodNumTotal: 223.0,
      prodRate: 8.07,
      prodPerson: '0',
      prodPersonRate: 0.0,
      partsNum: 346.0,
      partsNumTotal: 1911.0,
      partsRate: 18.11,
      partsPerson: '0',
      partsPersonRate: 0.0,
      bigProdNum: 0.0,
      bigPartsNum: 0.0,
      mhour: '16',
      mhourArea: null,
      enum: 0.0
    }
  ],
  resp_code: 0,
  resp_msg: '',
  code: 0,
  msg: ''
};
